spring:
  datasource:
    url: jdbc:mysql://47.102.118.47:3306/test?useSSL=false
    username: root
    password: Sr841430159@
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8


swagger:
  enable: true