update park set leftup=3  , leftdown=1  where id ='A1' ;
update park set leftup=6  , leftdown=3 where id ='A2' ;
update park set leftup=9  , leftdown=6  where id ='A3' ;
update park set leftdown=10 , rightdown=9  where id ='A4' ;
update park set leftdown=11 , rightdown=10  where id ='A5' ;
update park set rightup= 11 , rightdown=8  where id ='A6' ;
update park set rightup=8  , rightdown=5  where id ='A7' ;
update park set rightup=5  , rightdown=2  where id ='A8' ;
update park set leftup=11  , rightup=10  , leftdown=8 , rightdown=7  where id ='B1' ;
update park set leftup=10 , rightup=9  , leftdown=7 , rightdown=6  where id ='B2' ;
update park set leftup=8  , rightup=7  , leftdown=5 , rightdown=4  where id ='B3' ;
update park set leftup=7  , rightup=6  , leftdown=4 , rightdown=3  where id ='B4' ;
update park set leftup=5  , rightup=4  , leftdown=2 , rightdown=0  where id ='B5' ;
update park set leftup=4  , rightup=3  , leftdown=0 , rightdown=1  where id ='B6' ;

create table lot(id int auto_increment primary key not null,code int not null ,parkid varchar(10) unique ,empty enum("yes","no"));
alter table lot add consitrant foreign key parkid references lot(id);
create table lot(id int auto_increment primary key not null,code int not null ,parkid varchar(10) unique ,empty enum("yes","no"),foreign key (parkid) references park(id))DEFAULT CHARSET=utf8;
insert into lot values (1,1,'A1','yes')
insert into lot (code,parkid,empty)values (1,'A5','yes');
insert into lot (code,parkid,empty)values (2,'A5','yes');
insert into lot (code,parkid,empty)values (3,'A5','yes');
insert into lot (code,parkid,empty)values (1,'A4','yes');
insert into lot (code,parkid,empty)values (2,'A4','yes');
insert into lot (code,parkid,empty)values (3,'A4','yes');
insert into lot (code,parkid,empty)values (7,'A8','yes');
insert into lot (code,parkid,empty)values (8,'A8','yes');
insert into lot (code,parkid,empty)values (9,'A8','yes');
insert into lot (code,parkid,empty)values (10,'A8','yes');
insert into lot (code,parkid,empty)values (11,'A8','yes');
insert into lot (code,parkid,empty)values (12,'A8','yes');
insert into lot (code,parkid,empty)values (13,'A8','yes');
insert into lot (code,parkid,empty)values (14,'A8','yes');
insert into lot (code,parkid,empty)values (15,'A8','yes');
insert into lot (code,parkid,empty)values (16,'A8','yes');

insert into lot (code,parkid,empty,width,height)values (1,'A9','yes',2.5 ,5.3);
insert into lot (code,parkid,empty,width,height)values (2,'A9','yes',2.5 ,5.3);
insert into lot (code,parkid,empty,width,height)values (3,'A9','yes',2.5 ,5.3);
insert into lot (code,parkid,empty,width,height)values (1,'A10','yes',2.5 ,5.3);
insert into lot (code,parkid,empty,width,height)values (2,'A10','yes',2.5 ,5.3);
insert into lot (code,parkid,empty,width,height)values (3,'A10','yes',2.5 ,5.3);

insert into lot (code,parkid,empty)values (1,'B6','yes');
insert into lot (code,parkid,empty)values (2,'B6','yes');
insert into lot (code,parkid,empty)values (3,'B6','yes');
insert into lot (code,parkid,empty)values (4,'B6','yes');
insert into lot (code,parkid,empty)values (5,'B6','yes');
insert into lot (code,parkid,empty)values (6,'B6','yes');
insert into lot (code,parkid,empty)values (7,'B6','yes');
insert into lot (code,parkid,empty)values (8,'B6','yes');
insert into lot (code,parkid,empty)values (9,'B6','yes');
insert into lot (code,parkid,empty)values (10,'B6','yes');


insert into lot (code,parkid,empty,width,height,floor)values (1,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (2,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (3,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (4,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (5,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (6,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (7,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (8,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (9,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (10,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (11,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (12,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (13,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (14,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (15,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (16,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (17,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (18,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (19,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (20,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (21,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (22,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (23,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (24,'B7','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (25,'B7','yes',4,8,'二层');

insert into lot (code,parkid,empty,width,height,floor)values (1,'B8','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (2,'B8','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (3,'B8','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (4,'B8','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (5,'B8','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (6,'B8','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (7,'B8','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (8,'B8','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (9,'B8','yes',4,8,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (10,'B8','yes',4,8,'二层');

insert into lot (code,parkid,empty,width,height,floor)values (1,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (2,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (3,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (4,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (5,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (6,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (7,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (8,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (9,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (10,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (11,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (12,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (13,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (14,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (15,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (16,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (17,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (18,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (19,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (20,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (21,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (22,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (23,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (24,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (25,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (26,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (27,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (28,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (29,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (30,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (31,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (32,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (33,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (34,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (35,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (36,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (37,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (38,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (39,'A12','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (40,'A12','yes',2.5,5.3,'二层');

insert into lot (code,parkid,empty,width,height,floor)values (1,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (2,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (3,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (4,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (5,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (6,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (7,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (8,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (9,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (10,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (11,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (12,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (13,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (14,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (15,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (16,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (17,'A13','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (18,'A13','yes',2.5,5.3,'二层');

insert into lot (code,parkid,empty,width,height,floor)values (1,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (2,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (3,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (4,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (5,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (6,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (7,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (8,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (9,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (10,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (11,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (12,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (13,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (14,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (15,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (16,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (17,'A14','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (18,'A14','yes',2.5,5.3,'二层');


insert into lot (code,parkid,empty,width,height,floor)values (1,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (2,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (3,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (4,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (5,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (6,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (7,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (8,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (9,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (10,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (11,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (12,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (13,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (14,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (15,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (16,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (17,'A15','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (18,'A15','yes',2.5,5.3,'二层');

insert into lot (code,parkid,empty,width,height,floor)values (1,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (2,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (3,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (4,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (5,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (6,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (7,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (8,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (9,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (10,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (11,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (12,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (13,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (14,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (15,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (16,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (17,'A16','yes',2.5,5.3,'二层');
insert into lot (code,parkid,empty,width,height,floor)values (18,'A16','yes',2.5,5.3,'二层');